// Generated by view binder compiler. Do not edit!
package org.tensorflow.lite.examples.bertqa.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.tensorflow.lite.examples.bertqa.R;

public final class FragmentQaBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final InfoBottomSheetBinding bottomSheetLayout;

  @NonNull
  public final ConstraintLayout bottomView;

  @NonNull
  public final TextInputEditText edtQuestion;

  @NonNull
  public final ImageButton imgBtnAsk;

  @NonNull
  public final TextInputLayout inputLayout;

  @NonNull
  public final RecyclerView recyclerView;

  @NonNull
  public final TextView tvDatasetContent;

  @NonNull
  public final TextView tvInferenceTime;

  @NonNull
  public final TextView tvSuggestion;

  private FragmentQaBinding(@NonNull CoordinatorLayout rootView,
      @NonNull InfoBottomSheetBinding bottomSheetLayout, @NonNull ConstraintLayout bottomView,
      @NonNull TextInputEditText edtQuestion, @NonNull ImageButton imgBtnAsk,
      @NonNull TextInputLayout inputLayout, @NonNull RecyclerView recyclerView,
      @NonNull TextView tvDatasetContent, @NonNull TextView tvInferenceTime,
      @NonNull TextView tvSuggestion) {
    this.rootView = rootView;
    this.bottomSheetLayout = bottomSheetLayout;
    this.bottomView = bottomView;
    this.edtQuestion = edtQuestion;
    this.imgBtnAsk = imgBtnAsk;
    this.inputLayout = inputLayout;
    this.recyclerView = recyclerView;
    this.tvDatasetContent = tvDatasetContent;
    this.tvInferenceTime = tvInferenceTime;
    this.tvSuggestion = tvSuggestion;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentQaBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentQaBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_qa, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentQaBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.bottom_sheet_layout;
      View bottomSheetLayout = ViewBindings.findChildViewById(rootView, id);
      if (bottomSheetLayout == null) {
        break missingId;
      }
      InfoBottomSheetBinding binding_bottomSheetLayout = InfoBottomSheetBinding.bind(bottomSheetLayout);

      id = R.id.bottomView;
      ConstraintLayout bottomView = ViewBindings.findChildViewById(rootView, id);
      if (bottomView == null) {
        break missingId;
      }

      id = R.id.edtQuestion;
      TextInputEditText edtQuestion = ViewBindings.findChildViewById(rootView, id);
      if (edtQuestion == null) {
        break missingId;
      }

      id = R.id.imgBtnAsk;
      ImageButton imgBtnAsk = ViewBindings.findChildViewById(rootView, id);
      if (imgBtnAsk == null) {
        break missingId;
      }

      id = R.id.inputLayout;
      TextInputLayout inputLayout = ViewBindings.findChildViewById(rootView, id);
      if (inputLayout == null) {
        break missingId;
      }

      id = R.id.recyclerView;
      RecyclerView recyclerView = ViewBindings.findChildViewById(rootView, id);
      if (recyclerView == null) {
        break missingId;
      }

      id = R.id.tvDatasetContent;
      TextView tvDatasetContent = ViewBindings.findChildViewById(rootView, id);
      if (tvDatasetContent == null) {
        break missingId;
      }

      id = R.id.tvInferenceTime;
      TextView tvInferenceTime = ViewBindings.findChildViewById(rootView, id);
      if (tvInferenceTime == null) {
        break missingId;
      }

      id = R.id.tvSuggestion;
      TextView tvSuggestion = ViewBindings.findChildViewById(rootView, id);
      if (tvSuggestion == null) {
        break missingId;
      }

      return new FragmentQaBinding((CoordinatorLayout) rootView, binding_bottomSheetLayout,
          bottomView, edtQuestion, imgBtnAsk, inputLayout, recyclerView, tvDatasetContent,
          tvInferenceTime, tvSuggestion);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
