// Generated by view binder compiler. Do not edit!
package org.tensorflow.lite.examples.bertqa.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckedTextView;
import android.widget.RelativeLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.tensorflow.lite.examples.bertqa.R;

public final class ItemQuestionBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final CheckedTextView tvQuestionSuggestion;

  private ItemQuestionBinding(@NonNull RelativeLayout rootView,
      @NonNull CheckedTextView tvQuestionSuggestion) {
    this.rootView = rootView;
    this.tvQuestionSuggestion = tvQuestionSuggestion;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemQuestionBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemQuestionBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_question, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemQuestionBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.tvQuestionSuggestion;
      CheckedTextView tvQuestionSuggestion = ViewBindings.findChildViewById(rootView, id);
      if (tvQuestionSuggestion == null) {
        break missingId;
      }

      return new ItemQuestionBinding((RelativeLayout) rootView, tvQuestionSuggestion);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
